apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: offensive-pipeline
spec:
  params:
    - name: username
      type: string
  tasks:
    - name: hello
      taskSpec:
        - name: echo
          image: alpine
          script: |
            #!/bin/sh
            echo "Hello World"
